project:
  type: website
  output-dir: docs

website:
  title: "Early-Life Stress and Impulsivity"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bryanathieret
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css